invoice/urls.py
from django.contrib import admin
from django.conf.urls import url
from invoice import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^$', views.LoginView.as_view(), name='sign_in'),
                  url(r'^new_user_registrion/', views.UserRegistrationView.as_view(), name='new_user_registrion'),
                  url(r'^dashboard/create_invoice/', views.InvoiceCreateView.as_view(), name='create_invoice'),
                  url(r'^invoices/', views.InvoiceListView.as_view(), name='my_invoices'),
                  url(r'^send_mail/(?P<invoice_id>[0-9]+)/', views.SendMailView.as_view(), name='send_mail'),
                  url(r'^delete_invoice/(?P<invoice_id>[0-9]+)', views.InvoiceDeleteView.as_view(),
                      name='delete_invoice'),
                  url(r'^download_invoice/(?P<invoice_id>[0-9]+)/', views.DownloadInvoiceView.as_view(),
                      name='download_invoice'),
                  url(r'^dashboard/invoice_detail/(?P<invoice_id>[0-9]+)/', views.InvoiceDetailView.as_view(),
                      name='invoice_detail'),
                  url(r'^logout/', views.LogoutView.as_view(), name='logout')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('invoice.urls'))
]

invoice/models.py
from django.db import models
from django.contrib.auth.models import User


class Invoice(models.Model):
    invoice_logo = models.ImageField(upload_to='images/invoice_img', null=True, blank=True)
    invoice_num = models.CharField(max_length=100, blank=True, null=True)
    user = models.ForeignKey(User, related_name="users", on_delete=models.CASCADE, null=True, blank=True)
    invoice_date = models.DateField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    invoice_from = models.CharField(max_length=100, blank=True, null=True)
    notes = models.CharField(max_length=100, blank=True, null=True)
    payment_terms = models.CharField(max_length=100, blank=True, null=True)
    terms_and_conditions = models.CharField(max_length=100, blank=True, null=True)
    billing_address = models.CharField(max_length=200, blank=True, null=True)
    shipping_address = models.CharField(max_length=200, blank=True, null=True)
    total = models.DecimalField(max_digits=20, decimal_places=3, blank=True, null=True)
    discount = models.DecimalField(max_digits=20, decimal_places=3, blank=True, null=True)
    shipping_charge = models.DecimalField(max_digits=20, decimal_places=3, blank=True, null=True)
    tax = models.DecimalField(max_digits=20, decimal_places=3, blank=True, null=True)
    balance_due = models.DecimalField(max_digits=20, decimal_places=3, blank=True, null=True)
    subtotal = models.DecimalField(max_digits=20, decimal_places=3, blank=True, null=True)
    amount_paid = models.DecimalField(max_digits=20, decimal_places=3, blank=True, null=True)


class InvoiceLine(models.Model):
    invoice = models.ForeignKey('Invoice', null=True, blank=True, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=150, blank=True, null=True)
    item_description = models.CharField(max_length=200, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=20, decimal_places=3, blank=True, null=True)
    line_total = models.DecimalField(max_digits=20, decimal_places=3, blank=True, null=True)

invoice/forms.py
from invoice.models import Invoice, InvoiceLine
from django import forms
from django.forms.models import inlineformset_factory


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = '__all__'


class InvoiceLineForm(forms.ModelForm):
    class Meta:
        model = InvoiceLine
        fields = ('item_name', 'item_description', 'quantity', 'price', 'line_total')
        labels = {
            'item_name': 'Item Name',
            'item_description': 'Item description',
            'quantity': 'Quantity',
            'price': 'Price',
            'line_total': 'Total'
        }


InvoiceLineFormSet = inlineformset_factory(Invoice, InvoiceLine, form=InvoiceLineForm, extra=1, can_delete=False)

invoice/views.py
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as log_out_user
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.core.mail import EmailMessage
from django.db import transaction
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, ListView
from weasyprint import HTML

from invoice.forms import InvoiceForm, InvoiceLineFormSet
from invoice.models import Invoice, InvoiceLine


class InvoiceListView(ListView):

    """
    Invoice list view
    """

    template_name = "invoice/invoices.html"
    paginate_by = 10

    def get_queryset(self):
        return Invoice.objects.filter(user_id=int(self.request.user.id)).order_by("-id")


class InvoiceCreateView(FormView):

    """
    Invoice create view
    """

    form_class = InvoiceForm
    template_name = "invoice/invoice.html"

    def get_context_data(self, **kwargs):
        context = super(InvoiceCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["invoice_form"] = InvoiceForm(self.request.POST, self.request.FILES)
            context["invoiceline_form"] = InvoiceLineFormSet(self.request.POST)
        else:
            context["invoice_form"] = InvoiceForm()
            context["invoiceline_form"] = InvoiceLineFormSet()
        return context

    @transaction.atomic
    def form_valid(self, form):
        context = self.get_context_data()
        invoice_form = context["invoice_form"]
        invoice_line_formset = InvoiceLineFormSet(self.request.POST)

        if invoice_form.is_valid() and invoice_line_formset.is_valid():
            invoice_obj = invoice_form.save(commit=False)
            invoice_obj.user = self.request.user
            invoice_obj.save()

            for form in invoice_line_formset:
                invoice_line_obj = form.save(commit=False)
                invoice_line_obj.invoice_id = invoice_obj.id
                invoice_line_obj.save()

            make_invoice_file(self.request, invoice_obj.id)
            return HttpResponseRedirect("/invoices/")


class InvoiceDetailView(View):

    """
    Invoice detail view
    """

    def get(self, request, *args, **kwargs):
        invoice_id = int(self.kwargs["invoice_id"])
        invoice_data = Invoice.objects.filter(id=int(invoice_id)).first()
        invoice_line_data = InvoiceLine.objects.filter(invoice_id=int(invoice_id))
        return render(
            request,
            "invoice/invoice_detail.html",
            {
                "invoice_data": invoice_data,
                "invoice_line_data": invoice_line_data,
                "base_url": request.build_absolute_uri(invoice_data.invoice_logo.url),
            },
        )


class SendMailView(View):

    """
    Send mail with invoice attachment
    """

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(SendMailView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        invoice_id = int(self.kwargs["invoice_id"])
        invoice_data = (
            Invoice.objects.filter(id=invoice_id).values("invoice_num").first()
        )
        file_name = "INV" + invoice_data["invoice_num"]
        mail = EmailMessage(
            "Thank you for invoicing with us!",
            "A new invoice has been created on your account. You may find a PDF of your invoice attached.",
            settings.EMAIL_HOST_USER,
            [self.request.user],
        )
        file_path = os.path.join(settings.MEDIA_ROOT, "invoice_pdf", file_name)
        if os.path.exists(file_path):
            fs = FileSystemStorage(file_path)
            with fs.open(file_path) as pdf:
                mail.attach(file_name, pdf.read())
        mail.send()
        messages.success(self.request, "Mail sent")
        return HttpResponseRedirect("/invoices/")


class DownloadInvoiceView(View):

    """
    Download invoice view
    """

    def get(self, request, *args, **kwargs):
        invoice_id = int(self.kwargs["invoice_id"])
        invoice_data = (
            Invoice.objects.filter(id=invoice_id).values("invoice_num").first()
        )
        file_name = "INV" + invoice_data["invoice_num"]
        file_path = os.path.join(settings.MEDIA_ROOT, "invoice_pdf", file_name)

        if os.path.exists(file_path):
            fs = FileSystemStorage(file_path)
            with fs.open(file_path) as pdf:
                response = HttpResponse(pdf, content_type="application/pdf")
                response["Content-Disposition"] = 'attachment; filename= "{}"'.format(
                    file_name
                )
                return response


class InvoiceDeleteView(View):

    """
    Delete invoice and involiceline releted to invoice from db
    """

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(InvoiceDeleteView, self).dispatch(request, *args, **kwargs)

    @transaction.atomic
    def get(self, request, *args, **kwargs):
        invoice_id = int(self.kwargs["invoice_id"])
        InvoiceLine.objects.filter(invoice_id=invoice_id).delete()
        invoice_data = Invoice.objects.filter(id=invoice_id).first()
        file_path = os.path.join(
            settings.MEDIA_ROOT, "invoice_pdf", "INV" + invoice_data.invoice_num
        )

        if os.path.exists(file_path):
            os.remove(file_path)

        invoice_data.delete()
        messages.success(self.request, "Invoice removed sucessfully")
        return HttpResponseRedirect("/invoices/")


def make_invoice_file(request, invoice_id):

    """
    when user create Invoice so we can generate invoice pdf in media location
    """
    invoice_data = Invoice.objects.filter(id=int(invoice_id)).first()
    invoice_line_data = InvoiceLine.objects.filter(invoice_id=int(invoice_id))
    file_path = os.path.join(settings.MEDIA_ROOT, "invoice_pdf")
    html_string = render_to_string(
        "invoice/download_invoice.html",
        {
            "invoice_data": invoice_data,
            "invoice_line_data": invoice_line_data,
            "base_url": request.build_absolute_uri(invoice_data.invoice_logo.url),
        },
    )
    html = HTML(string=html_string)
    final_path = file_path + "/" + ("INV" + invoice_data.invoice_num)
    html.write_pdf(target=final_path)
    return "sucesss"


class LoginView(View):

    """
    User login view
    """

    def get(self, request):
        return render(request, "invoice/login.html")

    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            if user.is_active:
                print(user, "user")
                login(request, user)
                return HttpResponseRedirect("/invoices")
        else:
            messages.error(request, "Invalid username or password")
            return render(request, "invoice/login.html")


class LogoutView(View):

    """
    Logout view
    """

    def get(self, request):
        log_out_user(self.request)
        return HttpResponseRedirect("/")


class UserRegistrationView(View):

    """
    New user registration view
    """

    def get(self, request):
        return render(request, "invoice/registration.html")

    def post(self, request):
        username = request.POST["username"]
        password = make_password(request.POST["password"])
        first_name = request.POST["first_name"]

        if (User.objects.filter(username=username).count()) >= 1:
            messages.error(request, "Username is already exits.")
            return render(request, "invoice/registration.html")

        user = User.objects.create(
            username=username, password=password, first_name=first_name
        )
        login(request, user)
        return HttpResponseRedirect("/invoices/")

templates/invoice/dashboard.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}    
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="crossorigin="anonymous"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static '/css/dashboard.css' %}" type="text/css">
</head>
<body>
    <div class="container bootdey">
<div class="email-app mb-4" style="min-height:500px;overflow: auto;">
    <nav>
        <ul class="nav">
            <li class="nav-item">
                <p>Welcome {{request.user.first_name}}!</p>
            </li>
            <li class="nav-item">
                <a class="nav-link"  style="cursor: pointer;" href="{% url 'my_invoices' %}"><i class="fa fa-inbox"></i>My invoices</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="cursor: pointer;" href="{% url 'create_invoice' %}"><i class="fa fa-rocket"></i>Create invoice</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout" style="cursor: pointer;"><i class="fa fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </nav>
    <main class="inbox">
    {% block content %}   {% endblock %}
    </main>

</body>
</html>

templates/invoice/download_invoice.html
<html>
<head>
  {% load static %}
  {% load crispy_forms_tags %}
  <title>Test</title>
  <style type="text/css">
    *
    {
      border: 0;
      box-sizing: content-box;
      color: inherit;
      font-family: inherit;
      font-size: inherit;
      font-style: inherit;
      font-weight: inherit;
      line-height: inherit;
      list-style: none;
      margin: 0;
      padding: 0;
      text-decoration: none;
      vertical-align: top;
    }

    /* content editable */

    *[contenteditable] { border-radius: 0.25em; min-width: 1em; outline: 0; }

    *[contenteditable] { cursor: pointer; }

    *[contenteditable]:hover, *[contenteditable]:focus, td:hover *[contenteditable], td:focus *[contenteditable], img.hover { background: #DEF; box-shadow: 0 0 1em 0.5em #DEF; }

    span[contenteditable] { display: inline-block; }

    /* heading */

    h1 { font: bold 100% sans-serif; letter-spacing: 0.5em; text-align: center; text-transform: uppercase; }

    /* table */

    table { font-size: 75%; table-layout: fixed; width: 100%; }
    table { border-collapse: separate; border-spacing: 2px; }
    th, td { border-width: 1px; padding: 0.5em; position: relative; text-align: left; }
    th, td { border-radius: 0.25em; border-style: solid; }
    th { background: #EEE; border-color: #BBB; }
    td { border-color: #DDD; }

    /* page */

    html { font: 16px/1 'Open Sans', sans-serif;}
    html {cursor: default; }

    /*body { box-sizing: border-box; height: 11in; margin: 0 auto; overflow: hidden; padding: 0.5in; width: 8.5in; }*/
    /*body { background: #FFF; border-radius: 1px; box-shadow: 0 0 1in -0.25in rgba(0, 0, 0, 0.5); }*/

    /* header */

    header { margin: 0 0 3em; }
    header:after { clear: both; content: ""; display: table; }

    header h1 { background: #000; border-radius: 0.25em; color: #FFF; margin: 0 0 1em; padding: 0.5em 0; }
    header address { float: left; font-size: 75%; font-style: normal; line-height: 1.25; margin: 0 1em 1em 0; }
    header address p { margin: 0 0 0.25em; }
    header span, header img { display: block; float: right; }
    header span { margin: 0 0 1em 1em; max-height: 25%; max-width: 60%; position: relative; }
    header img { max-height: 100%; max-width: 100%; }
    header input { cursor: pointer; -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)"; height: 100%; left: 0; opacity: 0; position: absolute; top: 0; width: 100%; }
    header #target {
      position: absolute; left: 0;right: 0;top: 0;bottom: 0;object-fit: cover;margin: 0 auto;
    }

    /* article */

    article, article address, table.meta, table.inventory { margin: 0 0 3em; }
    article:after { clear: both; content: ""; display: table; }
    article h1 { clip: rect(0 0 0 0); position: absolute; }

    article address { float: left; font-size: 125%; font-weight: bold; }

    /* table meta & balance */

    table.meta, table.balance { float: right; width: 36%; }
    table.meta:after, table.balance:after { clear: both; content: ""; display: table; }

    /* table meta */

    table.meta th { width: 40%; }
    table.meta td { width: 60%; }

    /* table items */

    table.inventory { clear: both; width: 100%; }
    table.inventory th { font-weight: bold; text-align: center; }

    table.inventory td:nth-child(1) { width: 26%; }
    table.inventory td:nth-child(2) { width: 38%; }
    table.inventory td:nth-child(3) { text-align: right; width: 12%; }
    table.inventory td:nth-child(4) { text-align: right; width: 12%; }
    table.inventory td:nth-child(5) { text-align: right; width: 12%; }

    /* table balance */

    table.balance th, table.balance td { width: 50%; }
    table.balance td { text-align: right; }

    /* aside */

    aside h1 { border: none; border-width: 0 0 1px; margin: 0 0 1em; }
    aside h1 { border-color: #999; border-bottom-style: solid; }

    /* javascript */

    .add, .cut
    {
      border-width: 1px;
      display: block;
      font-size: .8rem;
      padding: 0.25em 0.5em;  
      float: left;
      text-align: center;
      width: 0.6em;
    }

    .add, .cut
    {
      background: #9AF;
      box-shadow: 0 1px 2px rgba(0,0,0,0.2);
      background-image: -moz-linear-gradient(#00ADEE 5%, #0078A5 100%);
      background-image: -webkit-linear-gradient(#00ADEE 5%, #0078A5 100%);
      border-radius: 0.5em;
      border-color: #0076A3;
      color: #FFF;
      cursor: pointer;
      font-weight: bold;
      text-shadow: 0 -1px 2px rgba(0,0,0,0.333);
    }

    .add { margin: -2.5em 0 0; }

    .add:hover { background: #00ADEE; }

    .cut { opacity: 0; position: absolute; top: 0; left: -1.5em; }
    .cut { -webkit-transition: opacity 100ms ease-in; }

    tr:hover .cut { opacity: 1; }

    @media print {
      * { -webkit-print-color-adjust: exact; }
      html { background: none; padding: 0; }
      body { box-shadow: none; margin: 0; }
      span:empty { display: none; }
      .add, .cut { display: none; }
    }
    .invoice_logo
    {
      width: 27%;
        height: 113px;
        background: #f5f5f5;
        border-radius: 4px;
        text-align: center;
        padding: 50px 0 0;
        border: 1px solid rgba(0,0,0,.1);
        position: relative;
    }

    .invoice_logo .main {
        font-size: 1.2em;
        color: #777;
    }
    @page { margin: 0; }
  </style>
</head>
<body>
    <header>
      <h1>Invoice - {{invoice_data.invoice_num}} </h1>
      <div class="invoice_logo" style="float: left;">
        <div class="main">
          <img src="{{base_url}}" id="target">
        </div>
      </div>
    </header>
    <article>
      <h1>Recipient</h1>
      <table class="meta" style="float: left;">
        <td style="margin:10px;">{{invoice_data.invoice_from}}</td>
        <tr>
          <th><span>Bill To</span></th>
        </tr>
        <tr>
          <td>{% if invoice_data.billing_address %}{{invoice_data.billing_address}}{% endif %}</td>
        </tr>

        <tr>
          <th><span>Ship To</span></th>
        </tr>
        <tr>
          <td>{% if invoice_data.shipping_address %}{{invoice_data.shipping_address}}{% endif %}</td>
        </tr>
      </table>

      <table class="meta">
        <tr>
          <th><span>Invoice No #</span></th>
          <td>{{invoice_data.invoice_num}}</td>
        </tr>
        <tr>
          <th><span>Date</span></th>
          <td>{{invoice_data.invoice_date|date:"Y-m-d"}}</td>
        </tr>

        <tr>
          <th><span>Payment terms</span></th>
          <td>{{invoice_data.payment_terms}}</td>
        </tr>

        <tr>
          <th><span>Due date</span></th>
          <td>{{invoice_data.due_date|date:"Y-m-d"}}</td>
        </tr>
      </table>
      <div>
        <table class="inventory">
          <thead>
            <tr>
              <th><span>Item</span></th>
              <th><span>Description</span></th>
              <th><span>Quantity</span></th>
              <th><span>Rate</span></th>
              <th><span >Total</span></th>
            </tr>
          </thead>
          <tbody>
            {% for invoice_line in invoice_line_data %}
              <tr>
                <td>{% if invoice_line.item_name %}{{invoice_line.item_name}}{%else%}{%endif%}</td>
                <td>{% if invoice_line.item_description %}{{invoice_line.item_description}}{%else%}{%endif%}</td>
                <td>{% if invoice_line.quantity %}{{invoice_line.quantity}}{%else%}0{%endif%}</td>
                <td><span data-prefix>$</span>{% if invoice_line.price %}{{invoice_line.price}}{%else%}0.000{%endif%}</td>
                <td><span data-prefix>$</span>{% if invoice_line.line_total %}{{invoice_line.line_total}}{%else%}0.000{%endif%}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <div>
          <table class="meta" style="float: left;">
            <tr style="padding-bottom:10px">
              <th><span>Notes</span></th>
              <tr><td>{% if invoice_data.notes %}{{invoice_data.notes}}{%endif%}</td>
            </tr>
            <tr>
              <th><span>Terms</span></th>
              <tr><td>{% if invoice_data.terms_and_conditions %}{{invoice_data.terms_and_conditions}}{%endif%}</td>
            </tr>
          </table>

          <table class="balance" style="float: right;">
            <tr>
              <th><span>Subtotal</span></th>
              <td><span data-prefix>$</span>{% if invoice_data.subtotal %}{{invoice_data.subtotal}}{% else %}0.000{% endif %}</td>
            </tr>
            <tr>
              <th><span>Discount(%)</span></th>
              <td>{% if invoice_data.discount %}{{invoice_data.discount}}{% else %}0.000{% endif %}</td>
            </tr>
            <tr>
              <th><span>Tax(%)</span></th>
              <td>{% if invoice_data.tax %}{{invoice_data.tax}}{% else %}0.000{% endif %}</td>
            </tr>
            <tr>
              <th><span>Shipping charges</span></th>
              <td><span data-prefix>$</span>{% if invoice_data.tax %}{{invoice_data.tax}}{% else %}0.000{% endif %}</td>
            </tr>
            <tr>
              <th><span>Total</span></th>
              <td><span data-prefix>$</span>{% if invoice_data.total %}{{invoice_data.total}}{% else %}0.000{% endif %}</td>
            </tr>
            <tr>
              <th><span>Amount Paid</span></th>
              <td><span data-prefix>$</span>{% if invoice_data.amount_paid %}{{invoice_data.amount_paid}}{% else %}0.000{% endif %}</td>
            </tr>
            <tr>
              <th><span>Balance Due</span></th>
              <td><span data-prefix>$</span>{% if invoice_data.balance_due %}{{invoice_data.balance_due}}{% else %}0.000{% endif %}</td>
            </tr>
          </table>
        </div>
      </div>
    </article>

</body>
</html>

templates/invoice/invoice.html
{% extends "invoice/dashboard.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" href="{% static 'css/invoice.css' %}">
<body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <header>
        <h1>New Invoice</h1>
        <div class="invoice_logo" style="float: left;">
            <div class="main">
                <img id="target"/>
                <input type="file" name="invoice_logo" required="required" onchange="putImage();" id="select_image"
                       accept="image/*">
                <span></span> Add Your Logo
            </div>
        </div>
    </header>
    <article>
        <h1>Recipient</h1>
        <table class="meta" style="float: left;">
            <td style="margin:10px;"><input type="text" name="invoice_from"
                                            placeholder="Who is this invoice from? (required)" required="required"></td>
            <tr>
                <th><span>Bill To</span></th>
                <th><span>Ship To</span></th>
            </tr>
            <tr>
                <td><input type="text" name="billing_address" placeholder="Who is this invoice to? (required)"
                           required="required"></td>
                <td><input type="text" name="shipping_address" placeholder="(Optional)"></td>
            </tr>
        </table>

        <table class="meta">
            <tr>
                <th><span>Invoice No #</span></th>
                <td><input type="text" name="invoice_num"></td>
            </tr>
            <tr>
                <th><span>Date</span></th>
                <td><input type="date" name="invoice_date"></td>
            </tr>

            <tr>
                <th><span>Payment terms</span></th>
                <td><input type="text" name="payment_terms"></td>
            </tr>

            <tr>
                <th><span>Due date</span></th>
                <td><input type="date" name="due_date"></td>
            </tr>
        </table>
        {{invoiceline_form.management_form |crispy }}
        <div>
            <table id="invoice_table">
                <thead>
                {% for form in invoiceline_form %}
                {% for field in form %}
                    {% if field.label != "Id" and field.label != "Invoice" %}
                        <th>{{ field.label }}</th>
                    {% endif %}
                {% endfor %}
                </thead>
                <tbody>
                <tr class="test">
                    {% for field in form %}
                    {% if field.label != "Id" and field.label != "Invoice" %}
                        {% if forloop.first %}
                        <td><a class="cut">-</a>{{ field }}</td>
                        {% else %}
                        <td>{{ field }}</td>
                        {% endif %}
                    {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <a class="add-form-row">+</a>

            <div>
                <table class="meta" style="float: left;">
                    <tr style="padding-bottom:10px">
                        <th><span>Notes</span></th>
                    <tr>
                        <td><input type="text" name="notes"
                                   placeholder="Notes - any relevant information not already covered"></td>
                    </tr>
                    <tr>
                        <th><span>Terms</span></th>
                    <tr>
                        <td><input style="width:60%" type="text" name="terms_and_conditions"
                                   placeholder="Terms and conditions - late fees, payment methods, delivery schedule">
                        </td>
                    </tr>
                </table>

                <table class="balance" style="float: right;">
                    <tr>
                        <th><span>Subtotal</span></th>
                        <td><span data-prefix>$</span><input id="id_subtotal" readonly="readonly" name="subtotal"
                                                             value="0.000"></td>
                    </tr>
                    <tr>
                        <th><span>Discount(%)</span></th>
                        <td><input type="number" name="discount" id="id_discout" max="99" value="0.000"></td>
                    </tr>
                    <tr>
                        <th><span>Tax(%)</span></th>
                        <td><input type="number" name="tax" id="id_tax" value="0.000"></td>
                    </tr>
                    <tr>
                        <th><span>Shipping</span></th>
                        <td><span data-prefix>$</span><input type="number" name="shipping_charge"
                                                             id="id_shipping_charge" value="0.000"></td>
                    </tr>
                    <tr>
                        <th><span>Total</span></th>
                        <td><span data-prefix>$</span><input type="number" name="total" readonly="readonly"
                                                             id="id_total" value="0.000"></td>
                    </tr>
                    <tr>
                        <th><span>Amount Paid</span></th>
                        <td><span data-prefix>$</span><input type="number" name="amount_paid" id="id_amount_paid"
                                                             value="0.000"></td>
                    </tr>
                    <tr>
                        <th><span>Balance Due</span></th>
                        <td><span data-prefix>$</span><input type="number" name="balance_due" readonly="readonly"
                                                             id="id_balance_due" value="0.000"></td>
                    </tr>
                </table>
            </div>
        </div>
    </article>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
</body>
<script type="text/javascript" src="{% static 'js/invoice.js' %}"></script>
{% endblock %}